// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDhzgv3Y88mBpnnf9rCAqYIDxEvzTtRA',
    appId: '1:376433426679:web:80eeec654af745d9a953f2',
    messagingSenderId: '376433426679',
    projectId: 'flutter-lovers-nikbin',
    authDomain: 'flutter-lovers-nikbin.firebaseapp.com',
    storageBucket: 'flutter-lovers-nikbin.appspot.com',
    measurementId: 'G-2VZJTRFRKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3dXe27r09-Cj8izJ5BTouAIZB4hrxeU',
    appId: '1:376433426679:android:b9f1abebc44ca17ba953f2',
    messagingSenderId: '376433426679',
    projectId: 'flutter-lovers-nikbin',
    storageBucket: 'flutter-lovers-nikbin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSP10AUP4JWMFMecCOYbulSthpfUrl5g',
    appId: '1:376433426679:ios:d7c8d3ec4f312055a953f2',
    messagingSenderId: '376433426679',
    projectId: 'flutter-lovers-nikbin',
    storageBucket: 'flutter-lovers-nikbin.appspot.com',
    iosClientId: '376433426679-a6j04pqpbblfa7kk2jhks90a416umlii.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoversOrgin',
  );
}
